language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip install git+https://github.com/bioimage-io/python-bioimage-io.git@verify_spec

# command to run tests
script:
  - python -m pybio.spec verify-bioimageio-manifest manifest.bioimage.io.yaml
