name: verify-spec

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-spec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install pkg
        run: pip install git+https://github.com/bioimage-io/spec-bioimage-io.git
      - name: verify-spec
        run: python -m bioimageio.spec verify-bioimageio-manifest manifest.bioimage.io.yaml
