name: verify-spec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  verify-spec:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
      - name: verify-spec
        shell: bash -l {0}
        run: |
          pip install git+https://github.com/bioimage-io/python-bioimage-io.git
          python -m pybio.spec verify-bioimageio-manifest manifest.bioimage.io.yaml